# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

# Please consult the lectures
Vector is a 2d array where Matrix is a 3d array

**2. How to import `NumPy` library?**

In [ ]:
# To avoid overwriting the output, please code here
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [2]:
list_1 = [1,2,3,4,5]

In [4]:
# To avoid overwriting the output, please code here
arr = np.array(list_1)
arr

array([1, 2, 3, 4, 5])

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [6]:
# To avoid overwriting the output, please code here
aarray = np.arange(0,6,dtype=int)
aarray

array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [15]:
# To avoid overwriting the output, please code here
np.ones(5)*0

array([0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [12]:
# To avoid overwriting the output, please code here

np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [13]:
# To avoid overwriting the output, please code here
np.ones(5)

array([1., 1., 1., 1., 1.])

[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [15]:
# To avoid overwriting the output, please code here
np.ones(5)*10

array([10., 10., 10., 10., 10.])

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [18]:
# To avoid overwriting the output, please code here
np.arange(52,100,2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [19]:
# To avoid overwriting the output, please code here
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [22]:
# To avoid overwriting the output, please code here

# Generate a vector array of 25 numbers
vector_array = np.arange(25)

vector_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
# To avoid overwriting the output, please code here
# Convert the vector array into a 2-D matrix using reshape
matrix = vector_array.reshape(5, 5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# To avoid overwriting the output, please code here

In [ ]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**




In [24]:
# To avoid overwriting the output, please code here
np.array([[0.1, 0.2, 0.3, 0.4, 0.5],
          [0.6, 0.7, 0.8, 0.9, 1.0],
          [1.1, 1.2, 1.3, 1.4, 1.5],
          [1.6, 1.7, 1.8, 1.9, 2.0],
          [2.1, 2.2, 2.3, 2.4, 2.5]])

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [25]:
# To avoid overwriting the output, please code here

# Generate an array of 25 integers using linspace
array_1d = np.linspace(0, 24, 25, dtype=int)

# Reshape it into a 5x5 matrix
matrix = array_1d.reshape(5, 5)

# Print the matrix
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [31]:
# Please consult the lectures.
#arange() specifies a step size between values, while linspace() specifies the number of evenly spaced points between a start and end value.

# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

# Using arange
np.arange(0, 1, 0.2)  # Output: [0.  0.2 0.4 0.6 0.8]

# Using linspace
np.linspace(0, 1, 5)  # Output: [0.  0.25 0.5 0.75 1. ]


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**15. How to generate a single random integer number using NumPy built-in
function?**

In [34]:
# To avoid overwriting the output, please code here
np.random.randint(1,10)

7

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [35]:
# To avoid overwriting the output, please code here
matrix = np.random.rand(7, 5)
print(matrix)

[[0.70307018 0.18109051 0.81521437 0.78225454 0.57391978]
 [0.39852712 0.96241425 0.64319932 0.52730331 0.68057505]
 [0.57533329 0.9473941  0.17409183 0.03305215 0.76123715]
 [0.50282773 0.27813829 0.11533343 0.83553239 0.30813362]
 [0.69714433 0.61506385 0.03232048 0.9931512  0.54837231]
 [0.18682095 0.75131171 0.74781277 0.48001564 0.45013666]
 [0.23229326 0.19944773 0.72863956 0.06048534 0.94225981]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [37]:
# To avoid overwriting the output, please code here
5 * np.eye(5)

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck